SYSTEM_RULES = "\n".join([
    "today maps to current date, tomorrow maps to +1 day, day-after-tomorrow maps to +2 days",
    "周X maps to the nearest future weekday after current_time",
    "下周X maps to the matching weekday in the next natural week",
    "vague daypart without a concrete clock maps start_time to null",
    "explicit AM/PM or 上午/下午/晚上 clock is normalized only when unambiguous",
    "bare ambiguous clock such as 6点 maps start_time to null",
    "service_date must be a real YYYY-MM-DD calendar date",
    "start_time must be 00:00-23:59",
    "people must be an integer party count",
    "do not infer people from event names or menu quantity",
    "address preserves the user service address and no implicit city completion is allowed",
    "需要买菜 without explicit purchase responsibility maps ingredient_purchase to null",
    "budget mappings are exactly 800到1200 -> 800/1200, 不超过1000 -> null/1000, 最多1000 -> null/1000, 至少1000 -> 1000/null, 预算1000 -> null/1000, 1000左右 -> null/null, 大概1000 -> null/null",
    "dietary_constraints are inherited until explicitly changed",
    "required slots are service_date, start_time, people, address",
    "call find_chefs only after all required slots are non-null",
    "latest valid Tool Result controls chef_query_status",
    "search/matched maps to reply_type present_chef_candidates and preserves Tool candidate order",
    "search/no_match maps to reply_type inform_no_match and candidates []",
    "search/out_of_service_area maps to reply_type inform_out_of_service_area and candidates []",
    "search/error maps to reply_type booking_paused and no retry",
    "specific/available maps to reply_type confirm_specific_chef",
    "specific/unavailable maps to reply_type present_alternatives, preserves alternatives, and has no auto Top-1 semantics",
    "specific/not_found maps to reply_type inform_not_found and alternatives []",
    "specific/out_of_service_area maps to reply_type inform_out_of_service_area and alternatives []",
    "specific/error maps to reply_type booking_paused and no retry",
    "query dependency mutation invalidates prior Tool-derived chef facts",
    "candidate order must match Tool candidate or alternative order",
    "affirmative allowlist is exactly 确认, 可以, 好的, 就这样, 确认预约",
    "mutation dominates confirmation",
    "unrelated true requires reply_type handoff",
    "never claim booking/order creation or completion success",
])
